### ISSUE TITLE
prefix_hack crash

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#1]
Same problem that I reported in the old repository

Traceback (most recent call last):
  File ".\mconvert.py", line 37, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 128, in main
    code3, error = preproc.prefix_hack(code1)
  File "C:\Python27\lib\site-packages\matlab2cpp\preproc.py", line 16, in prefix_hack
    text = re.sub(r"[{}]", r"\\\1", text)
  File "C:\Python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Python27\lib\re.py", line 275, in filter
    return sre_parse.expand_template(template, match)
  File "C:\Python27\lib\sre_parse.py", line 802, in expand_template
    raise error, "invalid group reference"
sre_constants.error: invalid group reference

**Comment by jonathf** [comment]
Allerede fikset i forrige commit på mandag, men glemt å pushe. Pushet nå.
