### ISSUE TITLE
Fil(er) saknas

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#27]
e.g.

        Traceback (most recent call last):
          File "..\matlab2cpp\mconvert.py", line 4, in <module>
            import matlab2cpp
          File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 8, in <module>
            import collection
          File "C:\Python27\lib\site-packages\matlab2cpp\collection.py", line 5, in <module>
            from node import Node
          File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 3, in <module>
            import targets
          File "C:\Python27\lib\site-packages\matlab2cpp\targets\__init__.py", line 459, in <module>
            exec("import %s" % name[:-3])
          File "<string>", line 1, in <module>
          File "C:\Python27\lib\site-packages\matlab2cpp\targets\frowvec.py", line 1, in <module>
            from rowvec_common import *
        ImportError: No module named rowvec_common

**Comment by jonathf** [comment]
Solved in newest update.
