### ISSUE TITLE
Krascher i filer med structer

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#41]
Jag får nu krascher i filer som innehåller structer, e.g. før "ZSystem_FullIInversion.m":

16989  465   Comment       '% Default constraints\n'
17011  466   Assign        'constr.non_lin=[]'
17011  466     Fvar        'constr.non_lin'
17026  466     Expression  '[]'
17026  466     Matrix      '[]'
[[]]
17026  466     Vector      '[]'
17030  467   Assign        'constr.lb=[]'
17030  467     Fvar        'constr.lb'
Traceback (most recent call last):
  File ".\mconvert.py", line 53, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 115, in main
    tree = process.process(code1, disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 2307, in process
    prog = create_program()
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 89, in create_program
    cur, line = create_function(program, cur, line)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 313, in create_function
    cur, line = fill_codeblock(block, cur, line)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 441, in fill_codeblock
    cur, line = create_assign(block, cur, line, eq_loc)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 526, in create_assign
    cur, line = create_assign_variable(assign, cur, line, eq_loc)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 723, in create_assign_variable
    node.declare()
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 364, in declare
    node = struct[struct["names"].index(name)]
ValueError: 'constr' is not in list

**Comment by jonathf** [comment]
Struct handle var ikke helt pollert, nei.
Prøv nå.

**Comment by aronandersson** [comment]
Jag får fortfarande fel:

Traceback (most recent call last):
 File ".\mconvert.py", line 53, in 
tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
 File "C:\Python27\lib\site-packages\matlab2cpp__init__.py", line 149, in main
 tree.generate(disp=disp)
 File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 160, in generate
 target = targets.dict[backend]
 KeyError: 'struct'

Också i filer som inte har strukter

**Comment by jonathf** [comment]
Glemte å adde til struct filen. Min store svakhet.
