### ISSUE TITLE
TypeError: list indices must be integers, not NoneType

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#42]
Jag får krascher på alla filer:

cfg missing!
loading scope...
iterating 14806 nodes
iterating 14816 nodes
Traceback (most recent call last):
  File ".\mconvert.py", line 53, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 149, in main
    tree.generate(disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 170, in generate
    value = value(node)
  File "C:\Python27\lib\site-packages\matlab2cpp\targets\matrix.py", line 149, in Assign
    node.dim = 0
  File "C:\Python27\lib\site-packages\matlab2cpp\datatype.py", line 203, in __set__
    instance.prop["type"] = get_name(value, mem)
  File "C:\Python27\lib\site-packages\matlab2cpp\datatype.py", line 136, in get_name
    return dims[dim].intersection(mems[mem]).pop()
TypeError: list indices must be integers, not NoneType

**Comment by jonathf** [comment]
Merkelig. Jeg kjører EMIT_Proc_ZSystem_FullInversion.m feilfritt.

Kan du gi meg den minste koden du kan generere som lager feilmeldingen?

**Comment by aronandersson** [comment]
Det verkar vara relaterat till alla typer av statiskt initialiserade arrays, inte bara space delimited. Føljande kraschar, men den kommenterade linjen fungerar.

    function out = EMIT_Init_Output(in)
    
    out = [1,2];
    %out = [in(1),in(2)];
    
    return

**Comment by jonathf** [comment]
Prøv nå.

**Comment by aronandersson** [comment]
Ok, det fungerar nu.
