### ISSUE TITLE
Krasch i komplicerad multilinje statement

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#48]
function y = uhh(x)
    
    if(...
            (piT*(pr-refVector(t-1))<(QdeltaP_oneFreqDatHF(im,t,2)-refVector(t-1))&&...
            0.85*refDeltaP(t)>deltaP(t))&&...
            ((waitToLearn<=waitIndex)&&(waitIndex<=fromRestartFBased))&&...%detect at restart
            ((QdeltaP_oneFreqDatHF(im,t,2)-lRefPi)>0.1*abs(pr-lRefPi)||......%Going back
            QdeltaP_oneFreqDatHF(im,t,2)>=pr)&&...%dont change compare to Pr.
            QdeltaP_oneFreqDatHF(iMotor,t,2)>fT&&startFlag>100)
        x = y;
    end

    end

reading file...
building token-tree...
   0    0 Program
   0    1 Function        'function y = uhh(x)'
   0    1   Return        'y'
  16    1   Param         'x'
  19    1 Codeblock
Traceback (most recent call last):
  File ".\mconvert.py", line 38, in <module>
    comments=opt.comments)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 35, in main
    tree = process.process(code1, disp=disp, comments=comments)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 2321, in process
    prog = create_program()
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 89, in create_program
    cur, line = create_function(program, cur, line)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 313, in create_function
    cur, line = fill_codeblock(block, cur, line)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 411, in fill_codeblock
    cur, line = create_if(block, cur, line)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 879, in create_if
    end = findend_expression(cur)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 2038, in findend_expression
    k = findend_paren(k)
  File "C:\Python27\lib\site-packages\matlab2cpp\process.py", line 2258, in findend_paren
    assert False
AssertionError

**Comment by jonathf** [comment]
Fixed
