### ISSUE TITLE
"r" som variabelnamn

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#6]
Följande fil fungerar inte, kanske någon konflikt med hanteringen av linebreaks i Windows:

    function x = apply_cheb(A,b,r,n)
    
    
      iter = 0;                                 % initialization
    
      eigmax = r(2);
      eigmin = r(1);
    
      c = ( eigmax - eigmin ) / 2.0;
      d = ( eigmax + eigmin ) / 2.0;
      
      x = zeros(size(A,1),1);
    
      for iter = 1:n,                     % begin iteration
    
        z =  b;
     
        if ( iter > 1 )                        % direction vectors
           beta = ( c*alph / 2.0 )^2;
           alph = 1.0 / ( d - beta );
           p = z + beta*p;
        else
           p = z;
           alph = 2.0 / d;
        end
    
        x  = x + alph*p;                      % update approximation
    
        b = b - alph*A*p;
    
      end

reading file...
running preproc...
writing preproc...
building token-tree...
line 1:29 mismatched input 'r' expecting <INVALID>
line 3:7 no viable alternative at input 'r'
line 4:7 no viable alternative at input 'r'
Traceback (most recent call last):
  File ".\mconvert.py", line 39, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 150, in main
    tree = build("."+filename)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 45, in build
    walker.walk(listener, program)
  File "C:\Python27\lib\site-packages\antlr4\tree\Tree.py", line 172, in walk
    self.walk(listener, child)
  File "C:\Python27\lib\site-packages\antlr4\tree\Tree.py", line 172, in walk
    self.walk(listener, child)
  File "C:\Python27\lib\site-packages\antlr4\tree\Tree.py", line 172, in walk
    self.walk(listener, child)
  File "C:\Python27\lib\site-packages\antlr4\tree\Tree.py", line 172, in walk
    self.walk(listener, child)
  File "C:\Python27\lib\site-packages\antlr4\tree\Tree.py", line 170, in walk
    self.enterRule(listener, t)
  File "C:\Python27\lib\site-packages\antlr4\tree\Tree.py", line 184, in enterRule
    ctx.enterRule(listener)
  File "C:\Python27\lib\site-packages\matlab2cpp\MatlabParser.py", line 1520, in enterRule
    listener.enterFunction_params(self)
  File "C:\Python27\lib\site-packages\matlab2cpp\MatlabListener.py", line 132, in enterFunction_params
    name = ctx.ID(n).getText()
AttributeError: 'NoneType' object has no attribute 'getText'

**Comment by jonathf** [comment]
Solved(-ish)
