### ISSUE TITLE
Krasch vid funktionsanrop

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#62]
e.g.: 

    function p = foo()
    
       [dm] = forward_radon_freq(mc,dt,h,q,N,flow,fhigh);
    
    end

ger:

        Traceback (most recent call last):
      File ".\mconvert.py", line 26, in <module>
        tree = matlab2cpp.main(opt, args)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\__init__.py", line 45, in main
        unassigned = builder.load(filename)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 64, in load
        self.create_program(filename)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 230, in create_program
        cur, line = self.create_function(program, cur, line)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 425, in create_function
        cur, line = self.fill_codeblock(block, cur, line)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 467, in fill_codeblock
        cur, line = self.create_assigns(block, cur, line, eq_loc)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 590, in create_assigns
        return self.create_assign(parent, cur, line, eq_loc)
      File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 611, in create_assign
        assert self.code[cur] in letters
    AssertionError

**Comment by jonathf** [comment]
retur-liste med ett element hadde en bug. Fikset nå.
