### ISSUE TITLE
Lambda function crash

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#69]
Jag får en krasch när jag försöker använda lambdafunktioner, e.g.

function x = cgsolve(A, b)

x = A(b);

end

där A är en func_lambda, ger:

configuring cgsolve.m
configure tree
Traceback (most recent call last):
  File ".\mconvert.py", line 58, in <module>
    matlab2cpp.main(args)
  File "C:\Anaconda\lib\site-packages\matlab2cpp\__init__.py", line 66, in main
    builder.configure(suggest=2*args.suggest)
  File "C:\Anaconda\lib\site-packages\matlab2cpp\treebuilder.py", line 146, in configure
    node.parent[-1].declare.reference
AttributeError: 'Var' object has no attribute 'reference'

**Comment by jonathf** [comment]
Lambda får nå fått to separate handles.

Hvis funksjonen er definert skikkelig fylles template. F.eks.:

    std::function<void(int)> f = ...

Hvis, funksjon kun dukker opp so margument, fylles ikke templaten opp:

    std::function f
